spring:
  profiles:
    active: dev
oss:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI5tQNtBignKM1TQY4x6g9
  accessKeySecret: 73IxTwHjyW8Knts9feVTDdmM1rAstp
  bucketName: volunteer-management