spring:
  data:
    redis:
      database: 4
    mongodb:
      uri: mongodb://root:123456@localhost:27017/chat_gpt?authSource=admin
      auto-index-creation: true
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: debug
gpt:
  proxy:
    host: localhost
    port: 7890
